//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift4Interaktiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChannels
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ChannelId { get; set; }
        public string Channel { get; set; }
    }
}
